###############################################################################################################################################
###############################################################################################################################################
################################################################ SERVICES #####################################################################
###############################################################################################################################################
###############################################################################################################################################
services:
  global_web_resources-dev:
    container_name: global_tools_web-ressources-dev
    image: websites:resources
    build:
      context: .
    restart: always
    volumes:
      - ./app:/var/www/html
    ports: 
      - 4142:80
    networks:
      - web
      - resources
      
################################################################ NETWORKS #####################################################################
networks:
  web: 
    external: true 
  resources: 